export const augustEvents = [
  {
    id: 'youth-creative-camp',
    title: '🎨 Youth Creative Camp (Ages 9+)',
    description: 'Five-day creative camp with multiple projects using mixed media and resin. No drop-ins. Snacks and drinks provided daily.',
    date: 'August 4–8, 2025',
    time: '1:00 PM – 3:00 PM daily',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 10,
    isRSVP: false,
    price: '$200 per child',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-08-04')
  },
  {
    id: 'oxford-house-campout',
    title: 'WA Oxford House Campout',
    description: 'A statewide sober campout for Oxford House residents & alumni. Enjoy a beachside camping weekend with group meals and activities. Includes the annual Stan Timberlake softball tournament.',
    date: 'August 5-7, 2025',
    time: 'Weekend Campout',
    location: 'Twin Harbors State Park, Westport, WA',
    category: 'Camping',
    attendees: 45,
    isRSVP: false,
    registrationUrl: 'https://wa.oxfordhouse.us',
    sortDate: new Date('2025-08-05')
  },
  {
    id: 'glowing-waterfall',
    title: '🌊 Glowing Waterfall',
    description: 'Paint a glowing waterfall landscape. No experience needed. Supplies and snacks provided.',
    date: 'August 6, 2025',
    time: '6:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 7,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-08-06')
  },
  {
    id: 'scarlet-sunset',
    title: '🌅 Scarlet Sunset',
    description: 'Paint a vivid mountain sunset scene. Suitable for all ages.',
    date: 'August 8, 2025',
    time: '6:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 9,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-08-08')
  },
  {
    id: 'na-family-barbecue',
    title: 'NA Family Barbecue',
    description: 'A family-friendly recovery BBQ hosted by NA (South Puget Sound Area). $10 per plate covers a full lunch; enjoy outdoor games and fellowship. Features a fun Family Feud game.',
    date: 'August 9, 2025',
    time: '11:00 AM - 3:00 PM',
    location: 'Weatherwood Private Park, 6708 33rd Ave SE, Lacey, WA',
    category: 'Social',
    attendees: 35,
    isRSVP: false,
    registrationUrl: 'https://spsana.org',
    sortDate: new Date('2025-08-09')
  },
  {
    id: 'moonlit-lake',
    title: '🌙 Moonlit Lake',
    description: 'Peaceful moonlit lake night scene. Great for beginners.',
    date: 'August 13, 2025',
    time: '6:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 6,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-08-13')
  },
  {
    id: 'otter-painting',
    title: '🦦 Otter Painting',
    description: 'Cute otter painting for all ages. Materials and snacks included.',
    date: 'August 15, 2025',
    time: '6:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 8,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-08-15')
  },
  {
    id: 'advanced-lighthouse',
    title: '🌊 Advanced Lighthouse (Intermediate Level)',
    description: 'Detailed lighthouse seascape. 4-hour class. More advanced but beginners welcome.',
    date: 'August 16, 2025',
    time: '11:00 AM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 5,
    isRSVP: false,
    price: '$60',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-08-16')
  },
  {
    id: 'sea-turtle',
    title: '🐢 Sea Turtle',
    description: 'Serene underwater turtle scene. All supplies included.',
    date: 'August 20, 2025',
    time: '6:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 7,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-08-20')
  },
  {
    id: 'lavender-fields',
    title: '💜 Lavender Fields',
    description: 'Blooming lavender fields painting. Peaceful and beginner-friendly.',
    date: 'August 22, 2025',
    time: '6:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 10,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-08-22')
  },
  {
    id: 'birch-forest',
    title: '🌳 Birch Forest',
    description: 'Calming birch tree forest. Step-by-step acrylic class.',
    date: 'August 23, 2025',
    time: '1:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 8,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-08-23')
  },
  {
    id: 'tropical-night',
    title: '🌴 Tropical Night',
    description: 'Paint a tropical moonlit beach or palm tree escape.',
    date: 'August 27, 2025',
    time: '6:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 9,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-08-27')
  },
  {
    id: 'golden-gateway',
    title: '🌅 Golden Gateway',
    description: 'Paint a golden-lit scenic entryway – magical and beginner-friendly.',
    date: 'August 30, 2025',
    time: '11:00 AM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 6,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-08-30')
  }
];