export const julyEvents = [
  {
    id: 'magenta-fields',
    title: '🌌 Magenta Fields',
    description: 'Bright magenta field with a night sky. Great for beginners. All supplies included.',
    date: 'July 16, 2025',
    time: '6:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 5,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-07-16')
  },
  {
    id: 'whale-sharks',
    title: '🐋 Whale Sharks',
    description: 'Paint an adorable whale shark scene. Beginner-friendly. Includes snacks and all materials.',
    date: 'July 17, 2025',
    time: '6:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 8,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-07-17')
  },
  {
    id: 'brushes-bevees',
    title: 'Brushes & Bevees: Zero-Proof Paint & Sip',
    description: 'An alcohol-free paint-and-sip workshop. Create a piece of art to take home while enjoying zero-proof beverages in a fun group setting. All art materials are provided.',
    date: 'July 18, 2025',
    time: '7:00 PM - 9:00 PM',
    location: 'Sober AF Bottle Shop, 5222 S Tacoma Way, Tacoma, WA',
    category: 'Art & Creativity',
    attendees: 12,
    isRSVP: false,
    registrationUrl: 'https://thesobercurator.com',
    sortDate: new Date('2025-07-18')
  },
  {
    id: 'viking-knit',
    title: '🛠️ Viking Knit Bracelet (Wire Weaving Class)',
    description: 'Learn ancient Viking wire weaving and take home your bracelet plus tools. Includes lunch break and snacks.',
    date: 'July 26, 2025',
    time: '11:00 AM – 5:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 6,
    isRSVP: false,
    price: '$90',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-07-26')
  },
  {
    id: 'living-room-picnic',
    title: 'Living Room Sober Picnic & BBQ',
    description: 'Fun in the Sun summer potluck picnic hosted by the NA Living Room home group. Burgers and hot dogs provided – attendees are encouraged to bring a side dish, chairs, and games.',
    date: 'July 26, 2025',
    time: '12:00 PM - 5:00 PM',
    location: 'Fort Steilacoom Park (Shelter #1 by playground), Lakewood, WA',
    category: 'Social',
    attendees: 25,
    isRSVP: false,
    registrationUrl: 'https://pcana.org',
    sortDate: new Date('2025-07-26')
  },
  {
    id: 'lakefest-2025',
    title: 'Lakefest 2025 (Recovery Campout)',
    description: 'A 4-day clean & sober camping festival for the recovery community. This NA campout features fellowship in the outdoors, with activities like campfire meetings and a Saturday night fire dance.',
    date: 'July 31 - August 3, 2025',
    time: '4-Day Event',
    location: 'Camp Lakeview, 32919 Benbow Dr E, Graham, WA',
    category: 'Camping',
    attendees: 60,
    isRSVP: false,
    registrationUrl: 'https://pcana.org',
    sortDate: new Date('2025-07-31')
  }
];