export const septemberEvents = [
  {
    id: 'tropical-beach-getaway',
    title: '🏖️ Tropical Beach Getaway',
    description: 'Warm sunset beach scene to capture summer vibes.',
    date: 'September 5, 2025',
    time: '6:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 7,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-09-05')
  },
  {
    id: 'recovery-day-park',
    title: 'Recovery Day at the Park',
    description: 'A community recovery celebration hosted by the Salish Recovery Coalition. Features live music, recovery stories, wellness activities like yoga and naloxone training, plus resource booths.',
    date: 'September 6, 2025',
    time: '11:00 AM - 2:00 PM',
    location: 'Evergreen Rotary Park, 1500 Park Ave, Bremerton, WA',
    category: 'Community',
    attendees: 50,
    isRSVP: false,
    registrationUrl: 'https://facebook.com',
    sortDate: new Date('2025-09-06')
  },
  {
    id: 'recovery-5k',
    title: 'Recovery 5K Run/Walk',
    description: 'A 5-kilometer fun run/walk celebrating resilience in recovery. Open to all fitness levels. Supports the Salish Recovery Coalition and fosters camaraderie in sobriety.',
    date: 'September 6, 2025',
    time: '9:00 AM start',
    location: 'Starts at Evergreen Park, Bremerton, WA',
    category: 'Fitness',
    attendees: 30,
    isRSVP: false,
    registrationUrl: 'https://findarace.com',
    sortDate: new Date('2025-09-06')
  },
  {
    id: 'wisteria-tree',
    title: '🌸 Wisteria Tree',
    description: 'Paint cascading wisteria flowers. Relaxing and colorful.',
    date: 'September 6, 2025',
    time: 'Time TBA',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 5,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-09-06')
  },
  {
    id: 'round-sunset',
    title: '🌇 Round Sunset',
    description: 'A circular composition sunset painting. Great for all skill levels.',
    date: 'September 10, 2025',
    time: '6:00 PM',
    location: 'Graffiti Creative Arts Center, 215 W Railroad Ave, Shelton, WA',
    category: 'Art & Creativity',
    attendees: 8,
    isRSVP: false,
    price: '$35',
    contact: '(360) 462-0220',
    registrationUrl: 'https://graffitiartcenter.com',
    sortDate: new Date('2025-09-10')
  },
  {
    id: 'fall-into-freedom',
    title: 'Fall into Freedom Recovery Fest',
    description: 'An afternoon recovery celebration in the park hosted by the Just 4 Today NA group as part of National Recovery Month. Expect sober fellowship, speakers, live music, and family-friendly activities.',
    date: 'September 13, 2025',
    time: '12:00 PM - 5:00 PM',
    location: 'Tumwater Historical Park (Lower Level), Tumwater, WA',
    category: 'Festival',
    attendees: 40,
    isRSVP: false,
    registrationUrl: 'https://spsana.org',
    sortDate: new Date('2025-09-13')
  },
  {
    id: 'recovery-day-mariners',
    title: 'Recovery Day at the Mariners',
    description: 'Join thousands in recovery at a Seattle Mariners baseball game! Kicks off with a 10:30 AM Recovery Rally at Occidental Square, then march to the stadium for pre-game festivities.',
    date: 'September 14, 2025',
    time: 'Rally 10:30 AM; Game 1:10 PM',
    location: 'T-Mobile Park, 1250 1st Ave S, Seattle, WA',
    category: 'Sports',
    attendees: 200,
    isRSVP: false,
    registrationUrl: 'https://thesobercurator.com',
    sortDate: new Date('2025-09-14')
  }
];